### ISSUE TITLE
[C64] question about pll reconfig

### ISSUE THREAD

**Issue by nippur72** [mist-devel/mist-board#105]
Not a real issue, perhaps a small simplification in the code.

I noticed the C64 core (and VIC20 and I suppose some other) has a pll reconfiguration mechanism for handling the case PAL/NTSC. I wonder why this has not been implemented simply as two outputs pll (`c0` and `c1`) since the Cyclone chip allows up to 4 clock outputs for the same pll.

Is there any particular reason?

And in case, is it worth to remove the pll reconfiguration and simplify the code? The selection of the frequency could be as simple as 
```
assign clk_sys = st_ntsc ? clk_sys_ntsc : clk_sys_pal;
```

**Comment by harbaum** [comment]
That's how it previously was. The problem is that you then have a combinatorial outout as a clock source which imho limits the usability of the dedicated clock networks inside the fpga. Using the reconfigurable pll allow to riute it's outputs directly to a clock network.

**Comment by nippur72** [comment]
ok, perfect thanks, that's a good reasonably reason. Still learning :-)

**Comment by sorgelig** [comment]
Actually, with simple 2 clocks selection like this Quartus automatically inserts special module "clock selector". So it won't be a combinatorial logic (there will be warning "Clock selector has been detected and protected."). At least how it's happened on Cyclone V. Since the intrinsic function has "cyclonev" in the name i'm not sure if the same function exists on Cyclone III device or it's Cyclone V specific. So, basically it may work. But the key point is precise PAL and NTSC clocks. It's impossible to use a single PLL with both these clocks with precise values. So 2 PLLs are required in this case.

**Comment by nippur72** [comment]
@sorgelig talking of precise clocks, is it possible to achieve exact frequencies (at 1 Hz resolution) by combining two plls in serial connection? E.g. the output of the first pll as input to a second one?

**Comment by sorgelig** [comment]
Yes, you can.

**Comment by gyurco** [comment]
Just saw this: _not_ using the clock multiplexer in C16 core halved the compile time. I think it's best to avoid it if you can.
