### ISSUE TITLE
Amstrad Core Issues

### ISSUE THREAD

**Issue by HartOz** [mist-devel/mist-board#45]
The core does not support the the bundled CP/M+ software.

With a valid working CP/M+ Disc1 image mounted,  the systems returns with the following message after issuing the |cpm command.

"This program will not run in this environment. Press any key"

Also there seems to be no way of adding a second floppy disk drive to the core.

**Comment by renaudhelias** [comment]
Nice, added to TODO-list

Second disk drive is implemented, running nice on some (but perhaps have to insert disk in both drives before trying second one), for sample STarKos run fine using two disk, and SymbOS also.

Bug reproduced

FDC has problems (it throws "Bad Command" instead of "Not Found")

**Comment by renaudhelias** [comment]
![cpmpluf1 dsk](https://cloud.githubusercontent.com/assets/13655988/24268879/99f9c0a8-100f-11e7-98b7-8d7098350eac.png)

Shown as solved about CP/M+, the message "This program will not run in this environment. Press any key" is due to using bad language localization, see cpmplus.zip at http://www.cpcwiki.eu/index.php/System_Disk

Can be closed.
