### ISSUE TITLE
Mice on atari core

### ISSUE THREAD

**Issue by gtranche** [mist-devel/mist-board#88]
Is there any news about mouse support on the atari core like on the minimig core ?
I tried som rs232 to usb cable with no success and i would like use my old mouse with my mist :)

**Comment by gyurco** [comment]
What kind of mouse is it? The original Atari mouse AFAIK is not RS232, but sends the quadrature motion detector signals to the joystick direction pins. That wouldn't be that hard to implement with the DB9 joystick ports.
But is there any value of an RS232 PC-mouse? What would motivate a developer to support those old cheap ball mice?

**Comment by harbaum** [comment]
The original Atari ST mouse delivers the same quadrature signal as an amiga mouse (only the wiring differs on two pins). This is evaluated by the so called ikbd processor in the Atari ST. The ikbd in turn is _not_ implemented in the core but in the MIST firmware (once i get really bored i'll implement it in the core). So this feature would have to be implemented entirely in the firmware. The reporting to the core would use the exact same logic that's currently using to send the signals derived from the USB mice.

A few things would have to be made configurable since the atari/mist cannot tell if there's a mouse connected or not.

**Comment by harbaum** [comment]
And yes, these are ball mice and they were prone to major defects. I doubt man of them exist in a satisfying state.

**Comment by gyurco** [comment]
Original Atari mice reported to work in the MiSTery core.
